### ISSUE TITLE
Braces to mark Globasa words in etymology & definition

### ISSUE THREAD

**Issue by PartialShawn** [ShawnPConroy/globasa-dictionary#9]
Globasa words in the etymology and definition marked with {braces} should link to the definition of that word. This may make the related words column unneeded.

**Comment by Ektor760** [comment]
Yes, this would be helpful, so that related words are generated automatically under each root word. Probably a good idea to do this for affixes as well, so that when we enter something like "day-" we would get the affix definition but also all words that use this particular affix. 

Would the braces also serve to prompt the program to make these words clickable?

**Comment by PartialShawn** [comment]
We have decided against this, braces were never added to the etymology, and instead it was requested that the etymology be broken apart as is back in Jan/Feb. So I will just automate the lookup on the etymology separating on the + symbol (for example)
